/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

/****LCD FUNCTIONS******
 *
 *	STEPS TO USE LCD FUNCTIONS
 *	STEP1. LCD_INIT();
 *	STEP2. ANY LCD FUNCTIONS CAN BE USED MENTIONED IN LCD.H
 */
#include "lcd.h"
#include <stdio.h>
#include "delay.h"
#include "keypad_init.h"
int main(void)
{
	char buf[100];
	char Input_str[]="val";
	uint8_t Input_data=0;
	LCD_INIT();
 KEYPAD_PINS_CONFIG();
 while(1)
 {
 Input_data	= DETECT_KEY_PRESS();
	sprintf(buf,"%s  %c",Input_str,Input_data);
	LCD_SEND_STRING(buf);
	LCD_DISPLAY_CLEAR();
	delay_ms(300);
 }
}




